<a href="https://colab.research.google.com/github/farihahahaa/farihahahaa/blob/main/FinalFunctions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Imports
**Tying to make the notebook cleaner**

In [1]:
import pandas as pd
import numpy as np
import glob # package that will help us grab all the pdfs in a folder
from pathlib import Path
from tqdm import tqdm
import re
import operator
import math
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import metrics
%matplotlib inline

pd.set_option("display.max_columns", 330)
pd.set_option('display.max_colwidth', None)

import warnings
warnings.filterwarnings("ignore")

!pip install pdfplumber -q
import pdfplumber

!pip install tabula-py
import tabula

from google.colab import drive

drive.mount('/content/gdrive', force_remount=True)

# Check if drive is already mounted
# import os
# if not os.path.exists('/content/gdrive'):
#   drive.mount("/content/gdrive") #force_remount=True
# else:
#   print("Drive is already mounted.")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.0/42.0 kB 626.5 kB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 kB 849.4 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.2/59.2 kB 1.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 33.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 24.5 MB/s eta 0:00:00
Collecting tabula-py
  Downloading tabula_py-2.9.3-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.10/dist-packages (from tabula-py) (2.1.4)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from tabula-py) (1.26.4)
Requirement already satisfied: distro in /usr/lib/python3/dist-packages (from tabula-py) (1.7.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.25.3->tabula-py) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.25.3->tabula-py) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.25.3->tabula-py) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->tabula-py) (1.16.0)
Downloading tabula_py-2.9.3-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 36.1 MB/s eta 0:00:00
Installing collected packages: tabula-py
Successfully installed tabula-py-2.9.3
Mounted at /content/gdrive

In [2]:
def extract_table_from_pdf(pdf_path, page_number, output_csv_path):
    """
    Extracts a table from a PDF and saves it as a CSV file.

    Parameters:
        pdf_path (str): Path to the PDF file.
        page_number (int): Page number to extract the table from.
        output_csv_path (str): Path to save the extracted table as a CSV file.
    """
    with pdfplumber.open(pdf_path) as pdf:
        # Get the specific page
        page = pdf.pages[page_number - 1]

        # Extract the table
        table = page.extract_table()

        if table:
            # Convert the table to a DataFrame
            df = pd.DataFrame(table[1:], columns=table[0])

            # Save the DataFrame to a CSV file
            df.to_csv(output_csv_path, index=False)
            print(f"Table extracted and saved to {output_csv_path}")
        else:
            print("No table found on the specified page.")

## Read PDF
**Read PDF from Drive**

In [3]:
app_779_4 = "/content/gdrive/MyDrive/Terner/PDFs/17-779.pdf"
app = app_779_4
pdf = pdfplumber.open(app)

csv_name = "779app_4%.csv"

In [4]:
app_37_9 = "/content/gdrive/MyDrive/Terner/PDFs/17-037.pdf"
app1 = app_37_9
pdf1 = pdfplumber.open(app1)

In [28]:
def find_table(pdf_path):
    # Open the PDF file using pdfplumber
    with pdfplumber.open(pdf_path) as pdf:
        # Iterate through all pages in the PDF
        for page_num, page in enumerate(pdf.pages):
            # Extract text from the page
            text = page.extract_text()
            # Check if the desired keyword is in the text
            if text and "Rental Subsidy Income/Operating Subsidy" in text:
                # Return the page number (pdfplumber is 0-indexed, so add 1)
                return page_num + 1

    # If the keyword is not found, return None
    return None

page_number = find_table(app1)
if page_number:
    print(f"The table is located on page {page_number}.")
else:
    print("The table was not found in the PDF.")

The table is located on page 17.

##Functions for each table

In [112]:
# cf_37 = extract_table_from_pdf(app_37, 12, "37app_9%.csv")
# cf_37 = pd.read_csv("37app_9%.csv")

# #when multiple tables on page:
# mr_37_ext = extract_table_from_pdf(app_37, 17, "37app_9%.csv")
# mr_37_1 = pd.DataFrame(pdf.pages[16].extract_tables()[0])

#df.fillna(-99, inplace=True)

###Construction Financing

In [56]:
def extract_cf(df):
  df = df.drop('Name of Lender/Source', axis=1)
  df = df.rename(columns={'Unnamed: 1': 'const_l1_name', 'Term (months)': 'const_l1_term', 'Interest Rate': 'const_l1_ir', 'Amount of Funds': 'const_l1_fund'})
  df.loc[0, 'const_funds_total'] = df.iloc[12, 3]
  df[['const_l1_name', 'const_l1_term', 'const_l1_ir', 'const_l1_fund']] = df[['const_l1_name', 'const_l1_term', 'const_l1_ir', 'const_l1_fund']].fillna(value=-99)
  df = df[:-1]
  return df

In [59]:
#9% page 12, 4% page 13
cf = extract_table_from_pdf(app1, 12, csv_name)
cf = pd.read_csv(csv_name)
cf_out = extract_cf(cf)
cf_out

Table extracted and saved to 779app_4%.csv

,const_l1_name,const_l1_term,const_l1_ir,const_l1_fund,const_funds_total
0,Boston Capital Finance - Const. Loan,24.0,4.000%,"$3,242,400","$5,596,904"
1,City of Lemoore - Fee Deferral,24.0,0.000%,"$230,200",nan
2,Hsg. Auth. of Kings County - Land Loan,24.0,0.000%,"$377,000",nan
3,"Pacific West Communities, Inc -DDF",24.0,0.000%,"$761,660",nan
4,Lemoore Pacific Assoc. III - Def. Costs,-99.0,-99,"$107,703",nan
5,Boston Capital - LIHTC Equity,-99.0,-99,"$877,941",nan
6,-99,-99.0,-99,-99,nan
7,-99,-99.0,-99,-99,nan
8,-99,-99.0,-99,-99,nan
9,-99,-99.0,-99,-99,nan
10,-99,-99.0,-99,-99,nan
11,-99,-99.0,-99,-99,nan

In [31]:
def process_column(column):
    return " | ".join(str(value) for value in column)

# replace the df cols are from!! 2x
processed_columns = [process_column(cf_out[col]) for col in cf_out.columns]

for processed_col in processed_columns:
    print(processed_col)

Bank of America, N.A. Loan | HCD HOME Loan | HCD IIG Funds - GP Loan | City of Winters Grant - Loan to LP | FHLB AHP Loan | Tax Credit Equity | Deferred Costs During Construction | -99 | -99 | -99 | -99 | -99
24.0 | 660.0 | 660.0 | 660.0 | 660.0 | -99.0 | -99.0 | -99.0 | -99.0 | -99.0 | -99.0 | -99.0
3.250% | 3.000% | 3.000% | 3.000% | 3.000% | -99 | -99 | -99 | -99 | -99 | -99 | -99
$10,000,000 | $2,173,572 | $1,800,000 | $1,243,497 | $900,000 | $1,008,980 | $1,939,070 | -99 | -99 | -99 | -99 | -99
$19,065,119 | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan

###Permanent Financing

In [17]:
def extract_pf(df):
  df = df.drop('Name of Lender/Source', axis=1)
  df = df.drop(['Residual\nReceipts /\nDeferred Pymt.', 'Annual Debt\nService'], axis=1, errors='ignore')
  df = df.rename(columns={'Unnamed: 1': 'perm_l1_name', 'Term\n(months)': 'perm_l1_term', 'Interest\nRate': 'perm_l1_ir',
  'Residual\nReceipts /\nDeferred Pymt.': 'Residual Receipts / Deferred Pymt.','Annual Debt\nService': 'Annual Debt Service', 'Amount of\nFunds': 'perm_l1_funds'})
  df.loc[0, 'perm_funds_total'] = df.iloc[12, 3]
  df.loc[0, 'tc_equity'] = df.iloc[13, 3]
  df.loc[0, 'projectfunds_total'] = df.iloc[14, 3]
  df = df[:-3]
  df[['perm_l1_name', 'perm_l1_term', 'perm_l1_ir', 'perm_l1_funds']] = df[['perm_l1_name', 'perm_l1_term', 'perm_l1_ir', 'perm_l1_funds']].fillna(value=-99)
  return df

In [18]:
#9% page 14, 4% page 15
pf = extract_table_from_pdf(app1, 14, csv_name)
pf = pd.read_csv(csv_name)
pf_out = extract_pf(pf)
pf_out

Table extracted and saved to 779app_4%.csv

,perm_l1_name,perm_l1_term,perm_l1_ir,perm_l1_funds,perm_funds_total,tc_equity,projectfunds_total
0,Boston Capital Finance - Perm Loan,480.0,6.000%,"$600,000","$1,207,200","$4,389,704","$5,596,904"
1,City of Lemoore - Fee Deferral,180.0,3.000%,"$230,200",nan,nan,nan
2,Hsg. Auth. of Kings County - Land Loan,660.0,2.000%,"$377,000",nan,nan,nan
3,-99,-99.0,-99,-99,nan,nan,nan
4,-99,-99.0,-99,-99,nan,nan,nan
5,-99,-99.0,-99,-99,nan,nan,nan
6,-99,-99.0,-99,-99,nan,nan,nan
7,-99,-99.0,-99,-99,nan,nan,nan
8,-99,-99.0,-99,-99,nan,nan,nan
9,-99,-99.0,-99,-99,nan,nan,nan
10,-99,-99.0,-99,-99,nan,nan,nan
11,-99,-99.0,-99,-99,nan,nan,nan

In [19]:
pf.columns

Index(['Name of Lender/Source', 'Unnamed: 1', 'Term\n(months)',
       'Interest\nRate', 'Residual\nReceipts /\nDeferred Pymt.',
       'Annual Debt\nService', 'Amount of\nFunds'],
      dtype='object')

In [13]:
def process_column(column):
    return " | ".join(str(value) for value in column)

# replace the df cols are from!! 2x
processed_columns = [process_column(pf_out[col]) for col in pf_out.columns]

for processed_col in processed_columns:
    print(processed_col)

Boston Capital Finance - Perm Loan | City of Lemoore - Fee Deferral | Hsg. Auth. of Kings County - Land Loan | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99
480.0 | 180.0 | 660.0 | -99.0 | -99.0 | -99.0 | -99.0 | -99.0 | -99.0 | -99.0 | -99.0 | -99.0
6.000% | 3.000% | 2.000% | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99
$600,000 | $230,200 | $377,000 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99
$1,207,200 | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan
$4,389,704 | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan
$5,596,904 | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan

###Income Info

In [35]:
def extract_inc(df):
  df = df.rename(columns={'(a)\nBedroom\nType(s)': 'BedroomType1', '(b)\nNumber of\nUnits': 'NumUnits1', '(c)\nProposed\nMonthly Rent\n(Less Utilities)': 'ProposedRent1',
  '(d)\nTotal Monthly\nRents\n(b x c)': 'TotalRents1','(e)\nMonthly\nUtility': 'MonthlyUtility1', '(f)\nMonthly Rent\nPlus Utilities\n(c + e)': 'RentPlusUtilities1',
  '(g)\n% of Targeted\nArea Median\nIncome': 'AMI1','(h)\n% of\nActual\nAMI': 'ActualAMI1'})
  df.loc[0, 'TotalUnits'] = df.iloc[25, 1]
  df.loc[0, 'TotalRent'] = df.iloc[25, 3]
  df.loc[0, 'AvgAMI'] = df.iloc[25, 6]
  df = df[:-1]
  df[['BedroomType1','NumUnits1', 'ProposedRent1', 'TotalRents1', 'MonthlyUtility1', 'RentPlusUtilities1', 'AMI1', 'ActualAMI1']] = df[['BedroomType1','NumUnits1', 'ProposedRent1', 'TotalRents1', 'MonthlyUtility1', 'RentPlusUtilities1', 'AMI1', 'ActualAMI1']].fillna(value=-99)
  return df

In [36]:
#9% page 16, 4% page 17
inc = extract_table_from_pdf(app, 17, csv_name)
inc = pd.read_csv(csv_name)
inc_out = extract_inc(inc)
inc_out

Table extracted and saved to 779app_4%.csv

,BedroomType1,NumUnits1,ProposedRent1,TotalRents1,MonthlyUtility1,RentPlusUtilities1,AMI1,ActualAMI1,TotalUnits,TotalRent,AvgAMI
0,1 Bedroom,4.0,$274,"$1,096",$76,$350,25%,25.0%,62.0,"$33,766",43.9%
1,1 Bedroom,2.0,$344,$688,$76,$420,30%,30.0%,NaN,nan,nan
2,1 Bedroom,14.0,$344,"$4,816",$76,$420,30%,30.0%,NaN,nan,nan
3,1 Bedroom,7.0,$484,"$3,388",$76,$560,40%,40.0%,NaN,nan,nan
4,1 Bedroom,16.0,$624,"$9,984",$76,$700,50%,50.0%,NaN,nan,nan
5,1 Bedroom,15.0,$764,"$11,460",$76,$840,60%,60.0%,NaN,nan,nan
6,2 Bedrooms,2.0,$415,$830,$89,$504,30%,30.0%,NaN,nan,nan
7,2 Bedrooms,2.0,$752,"$1,504",$89,$841,50%,50.0%,NaN,nan,nan
8,-99,-99.0,-99,-99,-99,-99,-99,-99,NaN,nan,nan
9,-99,-99.0,-99,-99,-99,-99,-99,-99,NaN,nan,nan
10,-99,-99.0,-99,-99,-99,-99,-99,-99,NaN,nan,nan
11,-99,-99.0,-99,-99,-99,-99,-99,-99,NaN,nan,nan
12,-99,-99.0,-99,-99,-99,-99,-99,-99,NaN,nan,nan
13,-99,-99.0,-99,-99,-99,-99,-99,-99,NaN,nan,nan
14,-99,-99.0,-99,-99,-99,-99,-99,-99,NaN,nan,nan
15,-99,-99.0,-99,-99,-99,-99,-99,-99,NaN,nan,nan
16,-99,-99.0,-99,-99,-99,-99,-99,-99,NaN,nan,nan
17,-99,-99.0,-99,-99,-99,-99,-99,-99,NaN,nan,nan
18,-99,-99.0,-99,-99,-99,-99,-99,-99,NaN,nan,nan
19,-99,-99.0,-99,-99,-99,-99,-99,-99,NaN,nan,nan
20,-99,-99.0,-99,-99,-99,-99,-99,-99,NaN,nan,nan
21,-99,-99.0,-99,-99,-99,-99,-99,-99,NaN,nan,nan
22,-99,-99.0,-99,-99,-99,-99,-99,-99,NaN,nan,nan
23,-99,-99.0,-99,-99,-99,-99,-99,-99,NaN,nan,nan
24,-99,-99.0,-99,-99,-99,-99,-99,-99,NaN,nan,nan

In [37]:
def process_column(column):
    return " | ".join(str(value) for value in column)

# replace the df cols are from!! 2x
processed_columns = [process_column(inc_out[col]) for col in inc_out.columns]

for processed_col in processed_columns:
    print(processed_col)

1 Bedroom | 1 Bedroom | 1 Bedroom | 1 Bedroom | 1 Bedroom | 1 Bedroom | 2 Bedrooms | 2 Bedrooms | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99
4.0 | 2.0 | 14.0 | 7.0 | 16.0 | 15.0 | 2.0 | 2.0 | -99.0 | -99.0 | -99.0 | -99.0 | -99.0 | -99.0 | -99.0 | -99.0 | -99.0 | -99.0 | -99.0 | -99.0 | -99.0 | -99.0 | -99.0 | -99.0 | -99.0
$274 | $344 | $344 | $484 | $624 | $764 | $415 | $752 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99
$1,096 | $688 | $4,816 | $3,388 | $9,984 | $11,460 | $830 | $1,504 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99
$76 | $76 | $76 | $76 | $76 | $76 | $89 | $89 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99
$350 | $420 | $420 | $560 | $700 | $840 | $504 | $841 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99
25% | 30% | 30% | 40% | 50% | 60% | 30% | 50% | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99
25.0% | 30.0% | 30.0% | 40.0% | 50.0% | 60.0% | 30.0% | 50.0% | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99 | -99
62.0 | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan
$33,766 | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan
43.9% | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan | nan

###Market Rate Units - 1

In [38]:
def extract_mr_0(df):
  new_header = df.iloc[0] #grab the first row for the header
  df = df[1:] #take the data less the header row
  df.columns = new_header
  df = df.rename(columns={'(a)\nBedroom\nType(s)': 'marketrate_BedroomType1', '(b)\nNumber of\nUnits': 'marketrate_NumUnits1', '(c)\nProposed\nMonthly Rent\n(Less Utilities)': 'marketrate_ProposedRent1',
    '(d)\nTotal Monthly\nRents\n(b x c)': 'marketrate_TotalMonthlyRents1','(e)\nMonthly\nUtility': 'MonthlyUtility1', '(f)\nMonthly Rent\nPlus Utilities\n(c + e)': 'RentPlusUtilities1',
    '(g)\n% of Targeted\nArea Median\nIncome': 'AMI1','(h)\n% of\nActual\nAMI': 'ActualAMI1'})
  df.fillna(-99, inplace=True)
  return df

In [39]:
#9% page 17, 4% page 18
#mr_ext = extract_table_from_pdf(app, 18, csv_name)
mr_1 = pd.DataFrame(pdf.pages[17].extract_tables()[0]) #subtract page by 1 for 4%
mr_1_out = extract_mr_0(mr_1)
mr_1_out

,marketrate_BedroomType1,marketrate_NumUnits1,marketrate_ProposedRent1,marketrate_TotalMonthlyRents1
1,,,,
2,,,,
3,,,,
4,,,,
5,,,,
6,,,,
7,,,,
8,,,,
9,,,,
10,,,,
11,Total # Units:,,Total:,

In [40]:
def process_column(column):
    return " | ".join(str(value) for value in column)

# replace the df cols are from!! 2x
processed_columns = [process_column(mr_1_out[col]) for col in mr_1_out.columns]

for processed_col in processed_columns:
    print(processed_col)

 |  |  |  |  |  |  |  |  |  | Total # Units:
 |  |  |  |  |  |  |  |  |  |
 |  |  |  |  |  |  |  |  |  | Total:
 |  |  |  |  |  |  |  |  |  |

###Market Rate Units - 2 (Totals)

In [41]:
def extract_mr(df):
  df = df.T
  new_header = df.iloc[0] #grab the first row for the header
  df = df[1:] #take the data less the header row
  df.columns = new_header
  df = df.rename(columns={'Aggregate Monthly Rents For All Units:': 'marketrate_AggMonthlyRents', 'Aggregate Annual Rents For All Units:': 'marketrate_AggAnnualRents'})
  df.fillna(-99, inplace=True)
  return df

In [42]:
#mr_ext = extract_table_from_pdf(app, 17, csv_name)
mr_2 = pd.DataFrame(pdf.pages[17].extract_tables()[1])
mr_2_out = extract_mr(mr_2)
mr_2_out

0 marketrate_AggMonthlyRents marketrate_AggAnnualRents
1                    $33,766                  $405,192

In [43]:
def process_column(column):
    return " | ".join(str(value) for value in column)

# replace the df cols are from!! 2x
processed_columns = [process_column(mr_2_out[col]) for col in mr_2_out.columns]

for processed_col in processed_columns:
    print(processed_col)

$33,766
$405,192

###Rental Subsidy Income/Operating Subsidy

In [44]:
def extract_rs(df):
  df = df.T
  new_header = df.iloc[0] #grab the first row for the header
  df = df[1:] #take the data less the header row
  df.columns = new_header
  df.rename(columns={ df.columns[2]: "contract_expire" }, inplace = True)
  df = df.rename(columns={'Number of Units Receiving Assistance:': 'assistance_units', 'Length of Contract (years):': 'contract_length', 'Total Projected Annual Rental Subsidy:': 'rentalsub_total'})
  df.fillna(-99, inplace=True)
  return df

In [45]:
#rs_ext = extract_table_from_pdf(app, 17, csv_name)
rs = pd.DataFrame(pdf.pages[17].extract_tables()[2])
rs_out = extract_rs(rs)
rs_out

0 assistance_units contract_length contract_expire rentalsub_total
1               22              15        2/1/2034        $130,920

In [46]:
def process_column(column):
    return " | ".join(str(value) for value in column)

# replace the df cols are from!! 2x
processed_columns = [process_column(rs_out[col]) for col in rs_out.columns]

for processed_col in processed_columns:
    print(processed_col)

22
15
2/1/2034
$130,920

##Return Column Values

**Tubed**

In [ ]:
# def process_column(column):
#     return " | ".join(str(value) for value in column)

# # replace the df cols are from!! 2x
# processed_columns = [process_column(df[col]) for col in df.columns]

# for processed_col in processed_columns:
#     print(processed_col)

##Final Function

pdf_path example:

```
app_779_4 = "/content/gdrive/MyDrive/Terner/PDFs/17-779.pdf"

```

possible table_names:
*Preferably with these capital letter, but must include correct spelling and "/" if applicable

1.   Construction Financing
2.   Permanent Financing
3.   Income Information
4.   Market Rate Units
5.   "Aggregate Monthly Rents For All Units" OR "Aggregate Annual Rents For All Units"
6.   Rental Subsidy Income/Operating Subsidy

sample csv_name:
format: # of application, app, and percentage type

```
# csv_name = "37app_9%.csv"
```

app_type: 4% or 9% application


```
# app_type = 4
# app_type = 9
```

In [104]:
#table_name should be a string!
def table_output(table_name, pdf_path, csv_name, app_type):
  pdf = pdfplumber.open(app)
  page_number = find_table(pdf_path)

  if (table_name == 'Construction Financing' or table_name.lower()=='construction financing') and app_type==4:
    cf = extract_table_from_pdf(pdf_path, 13, csv_name)
    cf = pd.read_csv(csv_name)
    # cf = cf.drop('Name of Lender/Source', axis=1)
    # cf = cf.drop(['Residual\nReceipts /\nDeferred Pymt.', 'Annual Debt\nService'], axis=1, errors='ignore')
    # if 'Term (months)' in cf.columns:
    #     cf = cf.rename(columns={'Unnamed: 1': 'const_l1_name', 'Term (months)': 'const_l1_term', 'Interest Rate': 'const_l1_ir', 'Amount of Funds': 'const_l1_fund'})
    # elif 'Term\n(months)' in cf.columns:
    #     cf = cf.rename(columns={'Unnamed: 1': 'const_l1_name', 'Term\n(months)': 'const_l1_term', 'Interest\nRate': 'const_l1_ir', 'Amount of\nFunds': 'const_l1_fund'})
    # cf.loc[0, 'const_funds_total'] = cf.iloc[12, 3]
    # cf[['const_l1_name', 'const_l1_term', 'const_l1_ir', 'const_l1_fund']] = cf[['const_l1_name', 'const_l1_term', 'const_l1_ir', 'const_l1_fund']].fillna(value=-99)
    # cf = cf[:-1]
    return cf

  elif (table_name == 'Construction Financing' or table_name.lower()=='construction financing') and app_type==9:
    cf = extract_table_from_pdf(pdf_path, 12, csv_name)
    cf = pd.read_csv(csv_name)
    cf = cf.drop('Name of Lender/Source', axis=1)
    cf = cf.drop(['Residual\nReceipts /\nDeferred Pymt.', 'Annual Debt\nService'], axis=1, errors='ignore')
    if 'Term (months)' in cf.columns:
        cf = cf.rename(columns={'Unnamed: 1': 'const_l1_name', 'Term (months)': 'const_l1_term', 'Interest Rate': 'const_l1_ir', 'Amount of Funds': 'const_l1_fund'})
    elif 'Term\n(months)' in cf.columns:
        cf = cf.rename(columns={'Unnamed: 1': 'const_l1_name', 'Term\n(months)': 'const_l1_term', 'Interest\nRate': 'const_l1_ir', 'Amount of\nFunds': 'const_l1_fund'})
    cf.loc[0, 'const_funds_total'] = cf.iloc[12, 3]
    cf[['const_l1_name', 'const_l1_term', 'const_l1_ir', 'const_l1_fund']] = cf[['const_l1_name', 'const_l1_term', 'const_l1_ir', 'const_l1_fund']].fillna(value=-99)
    cf = cf[:-1]
    return cf

  elif (table_name == 'Permanent Financing' or table_name.lower()=='permanent financing') and app_type==4:
    pf = extract_table_from_pdf(pdf_path, 15, csv_name)
    pf = pd.read_csv(csv_name)
    pf = pf.drop('Name of Lender/Source', axis=1)
    pf = pf.drop(['Residual\nReceipts /\nDeferred Pymt.', 'Annual Debt\nService'], axis=1, errors='ignore')
    pf = pf.rename(columns={'Unnamed: 1': 'perm_l1_name', 'Term\n(months)': 'perm_l1_term', 'Interest\nRate': 'perm_l1_ir',
    'Residual\nReceipts /\nDeferred Pymt.': 'Residual Receipts / Deferred Pymt.','Annual Debt\nService': 'Annual Debt Service', 'Amount of\nFunds': 'perm_l1_funds'})
    pf.loc[0, 'perm_funds_total'] = pf.iloc[12, 3]
    pf.loc[0, 'tc_equity'] = pf.iloc[13, 3]
    pf.loc[0, 'projectfunds_total'] = pf.iloc[14, 3]
    pf = pf[:-3]
    pf[['perm_l1_name', 'perm_l1_term', 'perm_l1_ir', 'perm_l1_funds']] = pf[['perm_l1_name', 'perm_l1_term', 'perm_l1_ir', 'perm_l1_funds']].fillna(value=-99)
    return pf

  elif (table_name == 'Permanent Financing' or table_name.lower()=='permanent financing') and app_type==9:
    pf = extract_table_from_pdf(pdf_path, 14, csv_name)
    pf = pd.read_csv(csv_name)
    pf = pf.drop('Name of Lender/Source', axis=1)
    pf = pf.drop(['Residual\nReceipts /\nDeferred Pymt.', 'Annual Debt\nService'], axis=1, errors='ignore')
    pf = pf.rename(columns={'Unnamed: 1': 'perm_l1_name', 'Term\n(months)': 'perm_l1_term', 'Interest\nRate': 'perm_l1_ir',
    'Residual\nReceipts /\nDeferred Pymt.': 'Residual Receipts / Deferred Pymt.','Annual Debt\nService': 'Annual Debt Service', 'Amount of\nFunds': 'perm_l1_funds'})
    pf.loc[0, 'perm_funds_total'] = pf.iloc[12, 3]
    pf.loc[0, 'tc_equity'] = pf.iloc[13, 3]
    pf.loc[0, 'projectfunds_total'] = pf.iloc[14, 3]
    pf = pf[:-3]
    pf[['perm_l1_name', 'perm_l1_term', 'perm_l1_ir', 'perm_l1_funds']] = pf[['perm_l1_name', 'perm_l1_term', 'perm_l1_ir', 'perm_l1_funds']].fillna(value=-99)
    return pf

  elif (table_name == 'INCOME INFORMATION' or table_name.lower()=="income information") and app_type==9:
    table_name = 'INCOME INFORMATION'
    inc = extract_table_from_pdf(pdf_path, 16, csv_name)
    inc = pd.read_csv(csv_name)
    inc = inc.rename(columns={'(a)\nBedroom\nType(s)': 'BedroomType1', '(b)\nNumber of\nUnits': 'NumUnits1', '(c)\nProposed\nMonthly Rent\n(Less Utilities)': 'ProposedRent1',
    '(d)\nTotal Monthly\nRents\n(b x c)': 'TotalRents1','(e)\nMonthly\nUtility': 'MonthlyUtility1', '(f)\nMonthly Rent\nPlus Utilities\n(c + e)': 'RentPlusUtilities1',
    '(g)\n% of Targeted\nArea Median\nIncome': 'AMI1','(h)\n% of\nActual\nAMI': 'ActualAMI1'})
    inc.loc[0, 'TotalUnits'] = inc.iloc[25, 1]
    inc.loc[0, 'TotalRent'] = inc.iloc[25, 3]
    inc.loc[0, 'AvgAMI'] = inc.iloc[25, 6]
    inc = inc[:-1]
    inc[['BedroomType1','NumUnits1', 'ProposedRent1', 'TotalRents1', 'MonthlyUtility1', 'RentPlusUtilities1', 'AMI1', 'ActualAMI1']] = inc[['BedroomType1','NumUnits1', 'ProposedRent1', 'TotalRents1', 'MonthlyUtility1', 'RentPlusUtilities1', 'AMI1', 'ActualAMI1']].fillna(value=-99)
    return inc

  elif (table_name == 'INCOME INFORMATION' or table_name.lower()=="income information") and app_type==4:
    table_name = 'INCOME INFORMATION'
    inc = extract_table_from_pdf(pdf_path, page_number-1, csv_name)
    inc = pd.read_csv(csv_name)
    inc = inc.rename(columns={'(a)\nBedroom\nType(s)': 'BedroomType1', '(b)\nNumber of\nUnits': 'NumUnits1', '(c)\nProposed\nMonthly Rent\n(Less Utilities)': 'ProposedRent1',
    '(d)\nTotal Monthly\nRents\n(b x c)': 'TotalRents1','(e)\nMonthly\nUtility': 'MonthlyUtility1', '(f)\nMonthly Rent\nPlus Utilities\n(c + e)': 'RentPlusUtilities1',
    '(g)\n% of Targeted\nArea Median\nIncome': 'AMI1','(h)\n% of\nActual\nAMI': 'ActualAMI1'})
    inc.loc[0, 'TotalUnits'] = inc.iloc[25, 1]
    inc.loc[0, 'TotalRent'] = inc.iloc[25, 3]
    inc.loc[0, 'AvgAMI'] = inc.iloc[25, 6]
    inc = inc[:-1]
    inc[['BedroomType1','NumUnits1', 'ProposedRent1', 'TotalRents1', 'MonthlyUtility1', 'RentPlusUtilities1', 'AMI1', 'ActualAMI1']] = inc[['BedroomType1','NumUnits1', 'ProposedRent1', 'TotalRents1', 'MonthlyUtility1', 'RentPlusUtilities1', 'AMI1', 'ActualAMI1']].fillna(value=-99)
    return inc

  elif (table_name == 'Market Rate Units' or table_name.lower()=="market rate units") and app_type==9:
    mr_1 = pd.DataFrame(pdf.pages[page_number].extract_tables()[0])
    new_header = mr_1.iloc[0] #grab the first row for the header
    mr_1 = mr_1[1:] #take the data less the header row
    mr_1.columns = new_header
    mr_1 = mr_1.rename(columns={'(a)\nBedroom\nType(s)': 'marketrate_BedroomType1', '(b)\nNumber of\nUnits': 'marketrate_NumUnits1', '(c)\nProposed\nMonthly Rent\n(Less Utilities)': 'marketrate_ProposedRent1',
    '(d)\nTotal Monthly\nRents\n(b x c)': 'marketrate_TotalMonthlyRents1','(e)\nMonthly\nUtility': 'MonthlyUtility1', '(f)\nMonthly Rent\nPlus Utilities\n(c + e)': 'RentPlusUtilities1',
    '(g)\n% of Targeted\nArea Median\nIncome': 'AMI1','(h)\n% of\nActual\nAMI': 'ActualAMI1'})
    mr_1.fillna(-99, inplace=True)
    return mr_1

  elif (table_name == 'Market Rate Units' or table_name.lower()=="market rate units") and app_type==4:
    mr_1 = pd.DataFrame(pdf.pages[17].extract_tables()[0])
    new_header = mr_1.iloc[0] #grab the first row for the header
    mr_1 = mr_1[1:] #take the data less the header row
    mr_1.columns = new_header
    mr_1 = mr_1.rename(columns={'(a)\nBedroom\nType(s)': 'marketrate_BedroomType1', '(b)\nNumber of\nUnits': 'marketrate_NumUnits1', '(c)\nProposed\nMonthly Rent\n(Less Utilities)': 'marketrate_ProposedRent1',
    '(d)\nTotal Monthly\nRents\n(b x c)': 'marketrate_TotalMonthlyRents1','(e)\nMonthly\nUtility': 'MonthlyUtility1', '(f)\nMonthly Rent\nPlus Utilities\n(c + e)': 'RentPlusUtilities1',
    '(g)\n% of Targeted\nArea Median\nIncome': 'AMI1','(h)\n% of\nActual\nAMI': 'ActualAMI1'})
    mr_1.fillna(-99, inplace=True)
    return mr_1

  elif (table_name == 'Aggregate Monthly Rents For All Units' or table_name == 'Aggregate Annual Rents For All Units') or (table_name.lower()=="aggregate monthly rents for all units" or table_name.lower()=="aggregate annual rents for all units") and app_type==4:
    mr_2 = pd.DataFrame(pdf.pages[page_number-1].extract_tables()[1])
    mr_2 = mr_2.T
    new_header = mr_2.iloc[0] #grab the first row for the header
    mr_2 = mr_2[1:] #take the data less the header row
    mr_2.columns = new_header
    mr_2 = mr_2.rename(columns={'Aggregate Monthly Rents For All Units:': 'marketrate_AggMonthlyRents', 'Aggregate Annual Rents For All Units:': 'marketrate_AggAnnualRents'})
    mr_2.fillna(-99, inplace=True)
    return mr_2

  elif (table_name == 'Aggregate Monthly Rents For All Units' or table_name == 'Aggregate Annual Rents For All Units') or (table_name.lower()=="aggregate monthly rents for all units" or table_name.lower()=="aggregate annual rents for all units") and app_type==9:
    mr_2 = pd.DataFrame(pdf.pages[page_number].extract_tables()[1])
    mr_2 = mr_2.T
    new_header = mr_2.iloc[0] #grab the first row for the header
    mr_2 = mr_2[1:] #take the data less the header row
    mr_2.columns = new_header
    mr_2 = mr_2.rename(columns={'Aggregate Monthly Rents For All Units:': 'marketrate_AggMonthlyRents', 'Aggregate Annual Rents For All Units:': 'marketrate_AggAnnualRents'})
    mr_2.fillna(-99, inplace=True)
    return mr_2

  elif (table_name == 'Rental Subsidy Income/Operating Subsidy' or table_name.lower()=="rental subsidy income/operating subsidy") and app_type==9:
    rs = pd.DataFrame(pdf.pages[page_number].extract_tables()[2])
    rs = rs.T
    new_header = rs.iloc[0] #grab the first row for the header
    rs = rs[1:] #take the data less the header row
    rs.columns = new_header
    rs.rename(columns={ rs.columns[2]: "contract_expire" }, inplace = True)
    rs = rs.rename(columns={'Number of Units Receiving Assistance:': 'assistance_units', 'Length of Contract (years):': 'contract_length', 'Total Projected Annual Rental Subsidy:': 'rentalsub_total'})
    rs.fillna(-99, inplace=True)
    return rs

  elif (table_name == 'Rental Subsidy Income/Operating Subsidy' or table_name.lower()=="rental subsidy income/operating subsidy") and app_type==4:
    rs = pd.DataFrame(pdf.pages[page_number-1].extract_tables()[2])
    rs = rs.T
    new_header = rs.iloc[0] #grab the first row for the header
    rs = rs[1:] #take the data less the header row
    rs.columns = new_header
    rs.rename(columns={ rs.columns[2]: "contract_expire" }, inplace = True)
    rs = rs.rename(columns={'Number of Units Receiving Assistance:': 'assistance_units', 'Length of Contract (years):': 'contract_length', 'Total Projected Annual Rental Subsidy:': 'rentalsub_total'})
    rs.fillna(-99, inplace=True)
    return rs

## Testing Function

In [76]:
# Construction Financing
# Permanent Financing
# Income Information
# Market Rate Units
# "Aggregate Monthly Rents For All Units" OR "Aggregate Annual Rents For All Units"
# Rental Subsidy Income/Operating Subsidy

In [109]:
csv_name1 = "37app_9%.csv" #app, 4 #app1=9
table_output('Rental Subsidy Income/Operating subsidy', app1, csv_name, 9)

0 assistance_units contract_length contract_expire rentalsub_total
1               22              15        2/1/2034        $130,920